import React, {
    lazy,
    Suspense,
    useCallback,
    useEffect,
    useMemo,
    useRef,
    useState,
} from 'react';
import {omit} from 'ramda';
import DatePickerSingle from '../components/DatePickerSingle';
import {
    DateRangeSliderProps,
    PersistedProps,
    PersistenceTypes,
    RangeSliderProps,
} from '../types';
import {
    dateStringToTimestamp,
    timestampToDateString,
    strAsDate,
    parseDisabledDates,
    snapToValidDate,
    enforceNoDisabledInBetween,
    MS_PER_DAY,
    MS_PER_MONTH,
    MS_PER_YEAR,
    formatDate,
    expandDisableFlags,
    dateAsStr,
    snapToStep,
} from '../utils/calendar/helpers';
import {autoGenerateDateMarks} from '../utils/computeDateSliderMarkers';
import rangeSlider from '../utils/LazyLoader/rangeSlider';

const RealSlider = lazy(rangeSlider);

/**
 * Slider component for selecting a date.
 * This is a wrapper around RangeSlider that handles date-to-timestamp conversions
 * and calendar-aware stepping via snapToValidDate().
 */
export default function DateRangeSlider({
    updatemode = 'mouseup',
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    persisted_props = [PersistedProps.value],
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    persistence_type = PersistenceTypes.local,
    // eslint-disable-next-line no-magic-numbers
    verticalHeight = 400,
    step,
    step_unit,
    marks,
    allow_direct_input = true,
    setProps,
    min,
    max,
    value,
    drag_value,
    pushable = false,
    disabled_dates,
    disable_flags,
    display_format,
    id,
    no_disabled_in_between = false,
    vertical = false,
    disabled_dates_indicator = true,
    ...props
}: DateRangeSliderProps) {
    const initialSortedValue = useRef([...(value ?? [])].sort());
    const minStr = min ?? initialSortedValue.current[0];
    const maxStr =
        max ??
        initialSortedValue.current[initialSortedValue.current.length - 1];

    // Convert min/max date strings to timestamps
    const mappedMin = useMemo(() => dateStringToTimestamp(minStr), [minStr]);
    const mappedMax = useMemo(() => dateStringToTimestamp(maxStr), [maxStr]);

    // Convert min/max date strings to dates
    const parsedMin = useMemo(() => strAsDate(minStr), [minStr]);
    const parsedMax = useMemo(() => strAsDate(maxStr), [maxStr]);

    // Convert deltas to timestamp
    const mappedStep = useMemo(() => {
        if (step && step_unit) {
            const msPerUnit =
                step_unit === 'years'
                    ? MS_PER_YEAR
                    : step_unit === 'months'
                    ? MS_PER_MONTH
                    : MS_PER_DAY;

            return step * msPerUnit;
        }
        if (step === null) {
            return null;
        }
        return MS_PER_DAY;
    }, [step, step_unit]);

    // Container ref and state for tracking slider width (used in auto-generating marks)
    const containerRef = useRef<HTMLDivElement>(null);
    const [sliderWidth, setSliderWidth] = useState<number | null>(null);
    useEffect(() => {
        if (!containerRef.current) {
            return undefined;
        }
        const observer = new ResizeObserver(entries => {
            const {width} = entries[0].contentRect;
            if (width > 0) {
                setSliderWidth(width);
            }
        });
        observer.observe(containerRef.current);
        return () => observer.disconnect();
    }, []);

    // Defines what marks are displayed on the slider
    const mappedMarks = useMemo(() => {
        // Explicit marks, convert date string keys to timestamps
        if (marks) {
            return Object.entries(marks).reduce<
                NonNullable<RangeSliderProps['marks']>
            >((acc, [dateStr, label]) => {
                const ts = dateStringToTimestamp(dateStr);
                if (typeof ts === 'number') {
                    acc[ts] = label;
                }
                return acc;
            }, {});
        }
        if (!parsedMin || !parsedMax) {
            return undefined;
        }
        return autoGenerateDateMarks(
            parsedMin,
            parsedMax,
            step,
            step_unit,
            display_format,
            sliderWidth
        );
    }, [
        marks,
        parsedMin,
        parsedMax,
        step,
        step_unit,
        display_format,
        sliderWidth,
    ]);

    // Convert date value to timestamp and wrap in array for RangeSlider
    const mappedValue: RangeSliderProps['value'] = useMemo(() => {
        if (Array.isArray(value)) {
            return value
                .map(dateStringToTimestamp)
                .filter((ts): ts is number => typeof ts === 'number');
        }
        const timestamp = dateStringToTimestamp(value);
        return typeof timestamp === 'number' ? [timestamp] : timestamp;
    }, [value]);

    // Convert drag_value to timestamp and wrap in array
    const mappedDragValue: RangeSliderProps['drag_value'] = useMemo(() => {
        if (Array.isArray(drag_value)) {
            return drag_value
                .map(dateStringToTimestamp)
                .filter((ts): ts is number => typeof ts === 'number');
        }
        const timestamp = dateStringToTimestamp(drag_value);
        return typeof timestamp === 'number' ? [timestamp] : timestamp;
    }, [drag_value]);

    // Convert pushable distance to timestamp
    const mappedPushable = useMemo(() => {
        if (typeof pushable === 'number') {
            const pushableMs = pushable * MS_PER_DAY;
            const stepMs = mappedStep || MS_PER_DAY;
            if (pushableMs < stepMs) {
                return 0;
            }
            return Math.round(pushableMs / stepMs);
        }
        return pushable;
    }, [pushable, mappedStep]);

    const {parsedDisabledDates, parsedDisabledRanges} = useMemo(
        () => parseDisabledDates(disabled_dates),
        [disabled_dates]
    );

    // Creates visual indicators for disabled dates/ranges
    const disabledIndicators = useMemo(() => {
        if (!parsedMin || !parsedMax) {
            return [];
        }

        // Helper to convert date to percentage position on slider
        const minTs = parsedMin.getTime();
        const totalRange = parsedMax.getTime() - minTs;
        const toPercent = (ts: number) =>
            Math.max(0, Math.min(100, ((ts - minTs) / totalRange) * 100));
        const singleWidth = (MS_PER_DAY / totalRange) * 100;

        // Expand disable_flags into individual dates and ranges
        const {dates: flagDates, ranges: flagRanges} = disable_flags
            ? expandDisableFlags(disable_flags, parsedMin, parsedMax)
            : {dates: [], ranges: []};

        const {parsedDisabledDates: allDates, parsedDisabledRanges: allRanges} =
            parseDisabledDates([
                ...(disabled_dates ?? []),
                ...flagRanges.map(([s, e]) => [dateAsStr(s)!, dateAsStr(e)!]),
                ...flagDates.map(d => dateAsStr(d)!),
            ]);

        return [
            ...(allRanges ?? []),
            ...(allDates?.map(d => [d, d] as [Date, Date]) ?? []),
        ].map(([start, end], index) => {
            // Calculate position and size of disabled range indicator
            const startPercent = toPercent(start.getTime());
            const endPercent = toPercent(end.getTime());
            const margin = singleWidth / 2;

            // Margin to make single-day disables visible
            const position = Math.max(0, startPercent - margin);
            const size = Math.min(100, endPercent + margin) - position;

            // Disabled range indicators render
            return (
                <div
                    key={`disabled-range-${index}`}
                    className="dash-slider-disabled-range"
                    style={
                        vertical
                            ? {bottom: `${position}%`, height: `${size}%`}
                            : {left: `${position}%`, width: `${size}%`}
                    }
                />
            );
        });
    }, [disabled_dates, disable_flags, parsedMin, parsedMax, vertical]);

    // Forces slider to reset to current value when marks change
    const [resetKey, setResetKey] = useState(0);

    const mappedValueRef = useRef(mappedValue);
    useEffect(() => {
        mappedValueRef.current = mappedValue;
    }, [mappedValue]);

    const prevDateValueRef = useRef<
        `${string}-${string}-${string}`[] | undefined
    >(value ?? undefined);

    // Converts what comes back from the RangeSlider (timestamps) into date strings to show the user
    const mappedSetProps: RangeSliderProps['setProps'] = useCallback(
        newProps => {
            const {value, drag_value} = newProps;
            const mappedProps: Partial<DateRangeSliderProps> = omit(
                ['min', 'max', 'step', 'value', 'drag_value', 'setProps'],
                newProps
            );
            if ('min' in newProps) {
                mappedProps.min = timestampToDateString(newProps.min);
            }
            if ('max' in newProps) {
                mappedProps.max = timestampToDateString(newProps.max);
            }
            if ('value' in newProps && value) {
                // Convert slider timestamps to date strings
                let rawDates = value
                    .map(raw => timestampToDateString(raw))
                    .filter(
                        (v): v is `${string}-${string}-${string}` =>
                            v !== undefined
                    );

                // If no_disabled_in_between enabled, prevents selection from crossing disabled dates
                const prev = prevDateValueRef.current;
                if (
                    no_disabled_in_between &&
                    rawDates.length === 2 &&
                    prev?.length === 2
                ) {
                    rawDates = enforceNoDisabledInBetween(
                        rawDates as [string, string],
                        prev as [string, string],
                        parsedMin,
                        parsedMax,
                        parsedDisabledDates,
                        parsedDisabledRanges,
                        disable_flags,
                        step,
                        step_unit,
                        marks
                    ) as `${string}-${string}-${string}`[];
                }

                // Snap each date to avoid disabled dates and align to step
                const snappedDates = rawDates
                    .map(dateStr => {
                        const r = strAsDate(dateStr);
                        if (!r) {
                            return undefined;
                        }
                        return timestampToDateString(
                            snapToValidDate(
                                r,
                                step,
                                step_unit,
                                parsedMin,
                                parsedMax,
                                parsedDisabledDates,
                                parsedDisabledRanges,
                                disable_flags,
                                marks
                            ).getTime()
                        );
                    })
                    .filter(
                        (v): v is `${string}-${string}-${string}` =>
                            v !== undefined
                    );

                // Update the value
                mappedProps.value = snappedDates;
                prevDateValueRef.current = snappedDates;

                // Check if value changed after snapping
                const snappedTs = snappedDates.map(dateStringToTimestamp);
                const noChange = snappedTs.every(
                    (ts, i) => ts === mappedValueRef.current?.[i]
                );
                // Reset slider to acknowledge interaction if no change happened
                if (noChange) {
                    setResetKey(k => k + 1);
                }
            }
            if ('drag_value' in newProps && drag_value) {
                mappedProps.drag_value = drag_value
                    .map(raw => timestampToDateString(raw))
                    .filter(
                        (v): v is `${string}-${string}-${string}` =>
                            v !== undefined
                    );
            }
            setProps(mappedProps);
        },
        [setProps]
    );

    // Timestamp to date conversion, respects display_format for tooltip and direct input
    useMemo(() => {
        const formatFuncName = `dateRangeSliderFormatDate_${id || 'default'}`;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const win = window as Record<string, any>;
        win.dccFunctions = win.dccFunctions || {};

        // Register the formatter function globally
        win.dccFunctions[formatFuncName] = (timestamp: number) => {
            try {
                const dateStr = timestampToDateString(timestamp);
                // Snap tooltip dates to step and valid dates to avoid showing disabled dates in tooltip
                const date = strAsDate(dateStr);
                if (!date) {
                    return `${timestamp}`;
                }
                const snapped = snapToStep(
                    date,
                    parsedMin ?? date,
                    step ?? 1,
                    step_unit ?? 'days'
                );
                return formatDate(snapped, display_format || 'YYYY-MM-DD');
            } catch (err) {
                return `${timestamp}`;
            }
        };
    }, [
        display_format,
        id,
        step,
        step_unit,
        parsedMin,
        parsedMax,
        parsedDisabledDates,
        parsedDisabledRanges,
        disable_flags,
    ]);

    // Display dates in tooltip using the formatter function
    const customTooltip = useMemo(() => {
        const formatFuncName = `dateRangeSliderFormatDate_${id || 'default'}`;
        const baseTooltip = props.tooltip || {
            placement: 'top',
            always_visible: false,
        };
        return {
            ...baseTooltip,
            template: '{value}',
            transform: formatFuncName,
        };
    }, [id, props.tooltip]);

    // Format values for display in custom inputs, compatible with date picker and display_format
    const displayValues = useMemo<
        [
            `${string}-${string}-${string}` | undefined,
            `${string}-${string}-${string}` | undefined
        ]
    >(() => {
        if (Array.isArray(value)) {
            return [value[0] ?? undefined, value[1] ?? undefined];
        }
        return [undefined, undefined];
    }, [value]);

    // Handle input changes for date inputs
    const handleDateInputChange = useCallback(
        (
            index: number,
            dateStr: `${string}-${string}-${string}` | undefined
        ) => {
            const newValue: `${string}-${string}-${string}`[] = [
                ...(Array.isArray(value) ? value : []),
            ];

            if (!dateStr) {
                newValue[index] = (
                    index === 0 ? minStr : maxStr
                ) as `${string}-${string}-${string}`;
                setProps({value: newValue});
                return;
            }

            // Parse input date string
            const inputDate = strAsDate(dateStr);
            if (!inputDate) {
                return;
            }

            // Snap to valid date, avoiding disabled dates and respecting step
            const snappedDate = snapToValidDate(
                inputDate,
                step,
                step_unit,
                parsedMin,
                parsedMax,
                parsedDisabledDates,
                parsedDisabledRanges,
                disable_flags,
                marks
            );
            // Convert snapped date to string format
            const snappedDateStr = dateAsStr(snappedDate) as
                | `${string}-${string}-${string}`
                | undefined;
            if (!snappedDateStr) {
                return;
            }

            // Check if the snapped date matches exactly what we already have in state
            const hasNoChange =
                Array.isArray(value) && value[index] === snappedDateStr;
            if (hasNoChange) {
                // ensures input corresponds to the snapped date even if user types a different but equivalent date
                setResetKey(k => k + 1);
            } else {
                // Update the value with the snapped date string
                newValue[index] = snappedDateStr;
                setProps({value: newValue});
            }
        },
        [
            value,
            setProps,
            minStr,
            maxStr,
            step,
            parsedMin,
            parsedMax,
            parsedDisabledDates,
            parsedDisabledRanges,
            disable_flags,
        ]
    );

    return (
        <div
            ref={containerRef}
            className="date-range-slider-container"
            data-vertical={vertical}
        >
            {allow_direct_input &&
                Array.isArray(value) &&
                value.length === 2 && (
                    <div className="dash-range-slider-min-input">
                        <DatePickerSingle
                            key={`min-input-${resetKey}`}
                            date={displayValues[0]}
                            setProps={({date}) =>
                                handleDateInputChange(0, date)
                            }
                            placeholder="Start date"
                            min_date_allowed={minStr}
                            max_date_allowed={maxStr}
                            display_format={display_format}
                        />
                    </div>
                )}
            <div className="dash-date-range-slider-wrapper">
                <Suspense fallback={null}>
                    <RealSlider
                        key={resetKey}
                        min={mappedMin}
                        max={mappedMax}
                        updatemode={updatemode}
                        verticalHeight={verticalHeight}
                        vertical={vertical}
                        step={mappedStep}
                        marks={mappedMarks}
                        allow_direct_input={false}
                        value={mappedValue}
                        drag_value={mappedDragValue}
                        setProps={mappedSetProps}
                        {...props}
                        pushable={mappedPushable}
                        tooltip={customTooltip}
                    />
                </Suspense>
                {disabled_dates_indicator && disabledIndicators.length > 0 && (
                    <div
                        className={`dash-slider-disabled-ranges-container ${
                            vertical ? 'vertical' : ''
                        }`.trim()}
                    >
                        {disabledIndicators}
                    </div>
                )}
            </div>
            {allow_direct_input &&
                Array.isArray(value) &&
                value.length === 2 && (
                    <div className="dash-range-slider-max-input">
                        <DatePickerSingle
                            key={`max-input-${resetKey}`}
                            date={displayValues[1]}
                            setProps={({date}) =>
                                handleDateInputChange(1, date)
                            }
                            placeholder="End date"
                            min_date_allowed={minStr}
                            max_date_allowed={maxStr}
                            display_format={display_format}
                        />
                    </div>
                )}
        </div>
    );
}

DateRangeSlider.dashPersistence = {
    persisted_props: [PersistedProps.value],
    persistence_type: PersistenceTypes.local,
};
