/* eslint-disable no-magic-numbers */
import {formatDate, stepDate} from './calendar/helpers';
import {SliderMarks, DateStepUnit} from '../types';

/** Selects a subset of dates that fit the slider width without label overlap. */
const estimateBestDateCount = (
    minDate: Date,
    maxDate: Date,
    dates: Date[],
    formatStr?: string,
    sliderWidth?: number | null
): {visible: Date[]; includeMax: boolean} => {
    if (dates.length <= 1) {
        return {visible: dates, includeMax: true};
    }

    // Estimate label pixel width from a sample formatted date to avoid overlap
    const effectiveWidth = sliderWidth || 330;
    const sampleLabel = formatDate(dates[0], formatStr);
    const maxLabelChars = sampleLabel.length;

    // Calculate required spacing based on label width
    // Estimate: 10px per character + 20px margin for spacing between labels
    // This provides comfortable spacing to prevent overlap
    const pixelsPerChar = 10;
    const spacingMargin = 20;
    const minPixelsPerMark = maxLabelChars * pixelsPerChar + spacingMargin;

    const targetCount = Math.max(
        2,
        Math.floor(effectiveWidth / minPixelsPerMark)
    );

    const totalRange = maxDate.getTime() - minDate.getTime();

    const middle = dates.filter(d => {
        const posFromMin =
            ((d.getTime() - minDate.getTime()) / totalRange) * effectiveWidth;
        return posFromMin >= minPixelsPerMark;
    });

    if (targetCount >= middle.length + 2) {
        const lastDate =
            middle.length > 0 ? middle[middle.length - 1] : minDate;
        const lastPosPx =
            ((lastDate.getTime() - minDate.getTime()) / totalRange) *
            effectiveWidth;

        return {
            visible: middle,
            includeMax: effectiveWidth - lastPosPx >= minPixelsPerMark,
        };
    }
    const innerTarget = targetCount - 2;
    if (innerTarget <= 0) {
        return {visible: [], includeMax: true};
    }

    const step = Math.ceil(middle.length / innerTarget);
    const result: Date[] = [];
    for (let i = 0; i < middle.length; i += step) {
        result.push(middle[i]);
    }

    const lastDate = result.length > 0 ? result[result.length - 1] : minDate;
    const lastPosPx =
        ((lastDate.getTime() - minDate.getTime()) / totalRange) *
        effectiveWidth;
    return {
        visible: result,
        includeMax: effectiveWidth - lastPosPx >= minPixelsPerMark,
    };
};

const toUtcTs = (date: Date) => {
    return Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
};

/** Generates slider marks for a date-based slider, mirroring autoGenerateMarks. */
export const autoGenerateDateMarks = (
    minDate: Date,
    maxDate: Date,
    step?: number | null,
    stepUnit?: DateStepUnit | null,
    formatStr?: string,
    sliderWidth?: number | null
) => {
    const minTs = toUtcTs(minDate);
    const maxTs = toUtcTs(maxDate);
    const s = step ?? 1;
    const u = stepUnit ?? 'days';

    // Iterate through all valid step positions between min and max
    const allDates: Date[] = [];
    for (let n = 1; ; n++) {
        const date = stepDate(minDate, s * n, u);
        if (!date || date.getTime() >= maxTs) {
            break;
        }
        allDates.push(date);
    }
    const {visible: visibleDates, includeMax} = estimateBestDateCount(
        minDate,
        maxDate,
        allDates,
        formatStr,
        sliderWidth
    );
    const dateMarks: SliderMarks = {};
    visibleDates.forEach(date => {
        dateMarks[toUtcTs(date)] = formatDate(date, formatStr);
    });

    const lastVisibleLabel =
        visibleDates.length > 0
            ? formatDate(visibleDates[visibleDates.length - 1], formatStr)
            : null;
    const maxLabel = formatDate(maxDate, formatStr);

    dateMarks[minTs] = formatDate(minDate, formatStr);
    if (includeMax && maxLabel !== lastVisibleLabel) {
        dateMarks[maxTs] = maxLabel;
    }
    return dateMarks;
};
