/* eslint-disable no-magic-numbers */
import {formatDate, stepDate} from './calendar/helpers';
import {SliderMarks} from '../types';

/** Selects a subset of dates that fit the slider width without label overlap. */
const estimateBestDateCount = (
    dates: Date[],
    formatStr?: string,
    sliderWidth?: number | null
): Date[] => {
    if (dates.length <= 2) {
        return dates;
    }

    // Estimate label pixel width from a sample formatted date to avoid overlap
    const effectiveWidth = sliderWidth || 330;
    const sampleLabel = formatDate(dates[0], formatStr);
    const maxLabelChars = sampleLabel.length;

    // Calculate required spacing based on label width
    // Estimate: 10px per character + 20px margin for spacing between labels
    // This provides comfortable spacing to prevent overlap
    const pixelsPerChar = 10;
    const spacingMargin = 20;
    const minPixelsPerMark = maxLabelChars * pixelsPerChar + spacingMargin;

    const targetCount = Math.max(
        2,
        Math.floor(effectiveWidth / minPixelsPerMark)
    );
    if (targetCount >= dates.length) {
        return dates;
    }
    const result: Date[] = [];
    for (let i = 0; i < targetCount; i++) {
        const idx = Math.round((i * (dates.length - 1)) / (targetCount - 1));
        result.push(dates[idx]);
    }
    return result;
};

const toUtcTs = (date: Date) => {
    return Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
};

/** Generates slider marks for a date-based slider, mirroring autoGenerateMarks. */
export const autoGenerateDateMarks = (
    minDate: Date,
    maxDate: Date,
    step?: string,
    formatStr?: string,
    sliderWidth?: number | null
) => {
    const minTs = toUtcTs(minDate);
    const maxTs = toUtcTs(maxDate);
    const s = step ? step : '0:0:1';

    // Iterate through all valid step positions between min and max
    const allDates: Date[] = [];
    let cursor = minDate;
    while (cursor.getTime() <= maxTs) {
        allDates.push(cursor);
        const next = stepDate(cursor, s);
        if (!next) {
            break;
        }
        cursor = next;
    }

    // Filter to a visible subset that fits without overlapping
    const visibleDates = estimateBestDateCount(
        allDates,
        formatStr,
        sliderWidth
    );

    const dateMarks: SliderMarks = {};
    visibleDates.forEach(date => {
        dateMarks[toUtcTs(date)] = formatDate(date, formatStr);
    });

    // Always include min and max regardless of density filtering
    dateMarks[minTs] = formatDate(minDate, formatStr);
    dateMarks[maxTs] = formatDate(maxDate, formatStr);

    return dateMarks;
};
