/* eslint-disable no-magic-numbers */
import {formatDate, stepDate} from './calendar/helpers';
import {SliderMarks, DateStepUnit} from '../types';

/** Selects a subset of dates that fit the slider width without label overlap. */
const estimateBestDateCount = (
    minDate: Date,
    maxDate: Date,
    dates: Date[],
    formatStr?: string,
    sliderWidth?: number | null
): Date[] => {
    if (dates.length <= 1) {
        return dates;
    }

    // Estimate label pixel width from a sample formatted date to avoid overlap
    const effectiveWidth = sliderWidth || 330;
    const sampleLabel = formatDate(dates[0], formatStr);
    const maxLabelChars = sampleLabel.length;

    // Calculate required spacing based on label width
    // Estimate: 10px per character + 20px margin for spacing between labels
    // This provides comfortable spacing to prevent overlap
    const pixelsPerChar = 10;
    const spacingMargin = 20;
    const minPixelsPerMark = maxLabelChars * pixelsPerChar + spacingMargin;

    const targetCount = Math.max(
        2,
        Math.floor(effectiveWidth / minPixelsPerMark)
    );

    const totalRange = maxDate.getTime() - minDate.getTime();
    const minGapPx = minPixelsPerMark / 1.5;
    const middle = dates.filter(d => {
        const posFromMin =
            ((d.getTime() - minDate.getTime()) / totalRange) * effectiveWidth;
        const posFromMax =
            ((maxDate.getTime() - d.getTime()) / totalRange) * effectiveWidth;
        return posFromMin >= minGapPx && posFromMax >= minGapPx;
    });

    if (targetCount >= middle.length + 2) {
        return middle;
    }
    const innerTarget = targetCount - 2;
    if (innerTarget <= 0) {
        return [];
    }

    const step = Math.ceil(middle.length / innerTarget);
    const result: Date[] = [];
    for (let i = 0; i < middle.length; i += step) {
        result.push(middle[i]);
    }
    return result;
};

const toUtcTs = (date: Date) => {
    return Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
};

/** Generates slider marks for a date-based slider, mirroring autoGenerateMarks. */
export const autoGenerateDateMarks = (
    minDate: Date,
    maxDate: Date,
    step?: number | null,
    stepUnit?: DateStepUnit | null,
    formatStr?: string,
    sliderWidth?: number | null
) => {
    const minTs = toUtcTs(minDate);
    const maxTs = toUtcTs(maxDate);
    const s = step ?? 1;
    const u = stepUnit ?? 'days';

    // Iterate through all valid step positions between min and max
    const allDates: Date[] = [];
    for (let n = 1; ; n++) {
        const date = stepDate(minDate, s * n, u);
        if (!date || date.getTime() >= maxTs) {
            break;
        }
        allDates.push(date);
    }

    const visibleDates = estimateBestDateCount(
        minDate,
        maxDate,
        allDates,
        formatStr,
        sliderWidth
    );
    const dateMarks: SliderMarks = {};
    visibleDates.forEach(date => {
        dateMarks[toUtcTs(date)] = formatDate(date, formatStr);
    });

    // Always include min and max regardless of density filtering
    dateMarks[minTs] = formatDate(minDate, formatStr);
    dateMarks[maxTs] = formatDate(maxDate, formatStr);

    return dateMarks;
};
