'use strict';

module.exports = {
    SETSELECTEDVALUE: 'SETSELECTEDVALUE',
    SETCHECKED: 'SETCHECKED',
    SETVALUE: 'SETVALUE',
    GETINITIALSTATE: 'GETINITIALSTATE',
    SERVERUPDATE: 'SERVERUPDATE',
    UPDATEGRAPH: 'UPDATEGRAPH',
    UPDATECOMPONENT: 'UPDATECOMPONENT',
    UNMARK_COMPONENT_AS_OUTDATED: 'UNMARK_COMPONENT_AS_OUTDATED'
};
