# AUTO GENERATED FILE - DO NOT EDIT

dashDataTable <- function(active_cell=NULL, columns=NULL, include_headers_on_copy_paste=NULL, locale_format=NULL, css=NULL, data=NULL, data_previous=NULL, data_timestamp=NULL, editable=NULL, end_cell=NULL, export_format=NULL, export_headers=NULL, fill_width=NULL, hidden_columns=NULL, id=NULL, is_focused=NULL, merge_duplicate_headers=NULL, fixed_columns=NULL, fixed_rows=NULL, column_selectable=NULL, row_deletable=NULL, row_selectable=NULL, selected_cells=NULL, selected_rows=NULL, selected_columns=NULL, selected_row_ids=NULL, start_cell=NULL, style_as_list_view=NULL, page_action=NULL, page_current=NULL, page_size=NULL, dropdown=NULL, dropdown_conditional=NULL, dropdown_data=NULL, tooltip=NULL, tooltip_conditional=NULL, tooltip_data=NULL, tooltip_delay=NULL, tooltip_duration=NULL, filter_query=NULL, filter_action=NULL, sort_action=NULL, sort_mode=NULL, sort_by=NULL, sort_as_null=NULL, style_table=NULL, style_cell=NULL, style_data=NULL, style_filter=NULL, style_header=NULL, style_cell_conditional=NULL, style_data_conditional=NULL, style_filter_conditional=NULL, style_header_conditional=NULL, virtualization=NULL, derived_filter_query_structure=NULL, derived_viewport_data=NULL, derived_viewport_indices=NULL, derived_viewport_row_ids=NULL, derived_viewport_selected_columns=NULL, derived_viewport_selected_rows=NULL, derived_viewport_selected_row_ids=NULL, derived_virtual_data=NULL, derived_virtual_indices=NULL, derived_virtual_row_ids=NULL, derived_virtual_selected_rows=NULL, derived_virtual_selected_row_ids=NULL) {
    
    props <- list(active_cell=active_cell, columns=columns, include_headers_on_copy_paste=include_headers_on_copy_paste, locale_format=locale_format, css=css, data=data, data_previous=data_previous, data_timestamp=data_timestamp, editable=editable, end_cell=end_cell, export_format=export_format, export_headers=export_headers, fill_width=fill_width, hidden_columns=hidden_columns, id=id, is_focused=is_focused, merge_duplicate_headers=merge_duplicate_headers, fixed_columns=fixed_columns, fixed_rows=fixed_rows, column_selectable=column_selectable, row_deletable=row_deletable, row_selectable=row_selectable, selected_cells=selected_cells, selected_rows=selected_rows, selected_columns=selected_columns, selected_row_ids=selected_row_ids, start_cell=start_cell, style_as_list_view=style_as_list_view, page_action=page_action, page_current=page_current, page_size=page_size, dropdown=dropdown, dropdown_conditional=dropdown_conditional, dropdown_data=dropdown_data, tooltip=tooltip, tooltip_conditional=tooltip_conditional, tooltip_data=tooltip_data, tooltip_delay=tooltip_delay, tooltip_duration=tooltip_duration, filter_query=filter_query, filter_action=filter_action, sort_action=sort_action, sort_mode=sort_mode, sort_by=sort_by, sort_as_null=sort_as_null, style_table=style_table, style_cell=style_cell, style_data=style_data, style_filter=style_filter, style_header=style_header, style_cell_conditional=style_cell_conditional, style_data_conditional=style_data_conditional, style_filter_conditional=style_filter_conditional, style_header_conditional=style_header_conditional, virtualization=virtualization, derived_filter_query_structure=derived_filter_query_structure, derived_viewport_data=derived_viewport_data, derived_viewport_indices=derived_viewport_indices, derived_viewport_row_ids=derived_viewport_row_ids, derived_viewport_selected_columns=derived_viewport_selected_columns, derived_viewport_selected_rows=derived_viewport_selected_rows, derived_viewport_selected_row_ids=derived_viewport_selected_row_ids, derived_virtual_data=derived_virtual_data, derived_virtual_indices=derived_virtual_indices, derived_virtual_row_ids=derived_virtual_row_ids, derived_virtual_selected_rows=derived_virtual_selected_rows, derived_virtual_selected_row_ids=derived_virtual_selected_row_ids)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'DataTable',
        namespace = 'dash_table',
        propNames = c('active_cell', 'columns', 'include_headers_on_copy_paste', 'locale_format', 'css', 'data', 'data_previous', 'data_timestamp', 'editable', 'end_cell', 'export_format', 'export_headers', 'fill_width', 'hidden_columns', 'id', 'is_focused', 'merge_duplicate_headers', 'fixed_columns', 'fixed_rows', 'column_selectable', 'row_deletable', 'row_selectable', 'selected_cells', 'selected_rows', 'selected_columns', 'selected_row_ids', 'start_cell', 'style_as_list_view', 'page_action', 'page_current', 'page_size', 'dropdown', 'dropdown_conditional', 'dropdown_data', 'tooltip', 'tooltip_conditional', 'tooltip_data', 'tooltip_delay', 'tooltip_duration', 'filter_query', 'filter_action', 'sort_action', 'sort_mode', 'sort_by', 'sort_as_null', 'style_table', 'style_cell', 'style_data', 'style_filter', 'style_header', 'style_cell_conditional', 'style_data_conditional', 'style_filter_conditional', 'style_header_conditional', 'virtualization', 'derived_filter_query_structure', 'derived_viewport_data', 'derived_viewport_indices', 'derived_viewport_row_ids', 'derived_viewport_selected_columns', 'derived_viewport_selected_rows', 'derived_viewport_selected_row_ids', 'derived_virtual_data', 'derived_virtual_indices', 'derived_virtual_row_ids', 'derived_virtual_selected_rows', 'derived_virtual_selected_row_ids'),
        package = 'dashTable'
        )

    structure(component, class = c('dash_component', 'list'))
}
