# AUTO GENERATED FILE - DO NOT EDIT

dashDataTable <- function(active_cell=NULL, columns=NULL, locale_format=NULL, content_style=NULL, css=NULL, data=NULL, data_previous=NULL, data_timestamp=NULL, editable=NULL, end_cell=NULL, id=NULL, is_focused=NULL, merge_duplicate_headers=NULL, n_fixed_columns=NULL, n_fixed_rows=NULL, row_deletable=NULL, row_selectable=NULL, selected_cells=NULL, selected_rows=NULL, selected_row_ids=NULL, start_cell=NULL, style_as_list_view=NULL, pagination_mode=NULL, pagination_settings=NULL, navigation=NULL, column_conditional_dropdowns=NULL, column_static_dropdown=NULL, column_static_tooltip=NULL, column_conditional_tooltips=NULL, tooltips=NULL, tooltip_delay=NULL, tooltip_duration=NULL, filter=NULL, filtering=NULL, filtering_type=NULL, filtering_types=NULL, sorting=NULL, sorting_type=NULL, sort_by=NULL, sorting_treat_empty_string_as_none=NULL, style_table=NULL, style_cell=NULL, style_data=NULL, style_filter=NULL, style_header=NULL, style_cell_conditional=NULL, style_data_conditional=NULL, style_filter_conditional=NULL, style_header_conditional=NULL, virtualization=NULL, derived_filter_structure=NULL, derived_viewport_data=NULL, derived_viewport_indices=NULL, derived_viewport_row_ids=NULL, derived_viewport_selected_rows=NULL, derived_viewport_selected_row_ids=NULL, derived_virtual_data=NULL, derived_virtual_indices=NULL, derived_virtual_row_ids=NULL, derived_virtual_selected_rows=NULL, derived_virtual_selected_row_ids=NULL, dropdown_properties=NULL) {
    
    component <- list(
        props = list(active_cell=active_cell, columns=columns, locale_format=locale_format, content_style=content_style, css=css, data=data, data_previous=data_previous, data_timestamp=data_timestamp, editable=editable, end_cell=end_cell, id=id, is_focused=is_focused, merge_duplicate_headers=merge_duplicate_headers, n_fixed_columns=n_fixed_columns, n_fixed_rows=n_fixed_rows, row_deletable=row_deletable, row_selectable=row_selectable, selected_cells=selected_cells, selected_rows=selected_rows, selected_row_ids=selected_row_ids, start_cell=start_cell, style_as_list_view=style_as_list_view, pagination_mode=pagination_mode, pagination_settings=pagination_settings, navigation=navigation, column_conditional_dropdowns=column_conditional_dropdowns, column_static_dropdown=column_static_dropdown, column_static_tooltip=column_static_tooltip, column_conditional_tooltips=column_conditional_tooltips, tooltips=tooltips, tooltip_delay=tooltip_delay, tooltip_duration=tooltip_duration, filter=filter, filtering=filtering, filtering_type=filtering_type, filtering_types=filtering_types, sorting=sorting, sorting_type=sorting_type, sort_by=sort_by, sorting_treat_empty_string_as_none=sorting_treat_empty_string_as_none, style_table=style_table, style_cell=style_cell, style_data=style_data, style_filter=style_filter, style_header=style_header, style_cell_conditional=style_cell_conditional, style_data_conditional=style_data_conditional, style_filter_conditional=style_filter_conditional, style_header_conditional=style_header_conditional, virtualization=virtualization, derived_filter_structure=derived_filter_structure, derived_viewport_data=derived_viewport_data, derived_viewport_indices=derived_viewport_indices, derived_viewport_row_ids=derived_viewport_row_ids, derived_viewport_selected_rows=derived_viewport_selected_rows, derived_viewport_selected_row_ids=derived_viewport_selected_row_ids, derived_virtual_data=derived_virtual_data, derived_virtual_indices=derived_virtual_indices, derived_virtual_row_ids=derived_virtual_row_ids, derived_virtual_selected_rows=derived_virtual_selected_rows, derived_virtual_selected_row_ids=derived_virtual_selected_row_ids, dropdown_properties=dropdown_properties),
        type = 'DataTable',
        namespace = 'dash_table',
        propNames = c('active_cell', 'columns', 'locale_format', 'content_style', 'css', 'data', 'data_previous', 'data_timestamp', 'editable', 'end_cell', 'id', 'is_focused', 'merge_duplicate_headers', 'n_fixed_columns', 'n_fixed_rows', 'row_deletable', 'row_selectable', 'selected_cells', 'selected_rows', 'selected_row_ids', 'start_cell', 'style_as_list_view', 'pagination_mode', 'pagination_settings', 'navigation', 'column_conditional_dropdowns', 'column_static_dropdown', 'column_static_tooltip', 'column_conditional_tooltips', 'tooltips', 'tooltip_delay', 'tooltip_duration', 'filter', 'filtering', 'filtering_type', 'filtering_types', 'sorting', 'sorting_type', 'sort_by', 'sorting_treat_empty_string_as_none', 'style_table', 'style_cell', 'style_data', 'style_filter', 'style_header', 'style_cell_conditional', 'style_data_conditional', 'style_filter_conditional', 'style_header_conditional', 'virtualization', 'derived_filter_structure', 'derived_viewport_data', 'derived_viewport_indices', 'derived_viewport_row_ids', 'derived_viewport_selected_rows', 'derived_viewport_selected_row_ids', 'derived_virtual_data', 'derived_virtual_indices', 'derived_virtual_row_ids', 'derived_virtual_selected_rows', 'derived_virtual_selected_row_ids', 'dropdown_properties'),
        package = 'dashTable'
        )

    component$props <- filter_null(component$props)

    structure(component, class = c('dash_component', 'list'))
}

