/* eslint-disable no-magic-numbers */
/**
 * Unit tests for dynamic slider mark density functionality
 * File is largely generated by Claude
 *
 * Tests the behavior implemented for width-based mark density where:
 * - 330px is the baseline width where 0-100 range with step=5 shows ~10 marks
 * - Wider sliders show more marks, narrower sliders show fewer marks
 * - All marks must be valid step positions (divisible by step value)
 * - Marks are properly spaced to avoid visual overlap
 */

import {SliderMarks} from '../../src/types';
import {sanitizeMarks} from '../../src/utils/computeSliderMarkers';

// Helper function to extract numeric mark positions
const getMarkPositions = (marks: SliderMarks): number[] => {
    if (!marks) {
        return [];
    }
    return Object.keys(marks)
        .map(Number)
        .sort((a, b) => a - b);
};

// Helper function to check if all marks are valid step positions
const areAllMarksValidSteps = (
    marks: SliderMarks,
    min: number,
    step: number
): boolean => {
    if (!marks) {
        return false;
    }
    const positions = getMarkPositions(marks);
    return positions.every(pos => {
        const stepsFromMin = Math.round((pos - min) / step);
        const expectedPosition = min + stepsFromMin * step;
        return Math.abs(pos - expectedPosition) === 0;
    });
};

describe('Dynamic Slider Mark Density', () => {
    describe('Baseline behavior (330px width)', () => {
        test('should show ~10-11 marks for 0-100 range with step=5', () => {
            const marks = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 330,
            });

            expect(marks).toBeDefined();
            const positions = getMarkPositions(marks);

            expect(positions.length).toBe(11);
            expect(areAllMarksValidSteps(marks, 0, 5)).toBe(true);
            expect(positions).toContain(0);
            expect(positions).toContain(100);
        });

        test('should include min and max values in marks', () => {
            const marks = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 330,
            });

            const positions = getMarkPositions(marks);

            expect(positions[0]).toBe(0);
            expect(positions[positions.length - 1]).toBe(100);
        });

        test('should show ~11 marks for 0-10 range at baseline width (330px)', () => {
            const marks = sanitizeMarks({
                min: 0,
                max: 10,
                marks: undefined,
                step: 1, // Step of 1 (equivalent to no step constraint)
                sliderWidth: 330,
            });

            expect(marks).toBeDefined();
            const positions = getMarkPositions(marks);

            // Should show ~11 marks regardless of range when at baseline width
            expect(positions.length).toBeGreaterThanOrEqual(9);
            expect(positions.length).toBeLessThanOrEqual(12);
            expect(positions).toContain(0);
            expect(positions).toContain(10);
        });

        test('should reduce density for large numbers to prevent label overlap (0-10000)', () => {
            const smallRange = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 10,
                sliderWidth: 330,
            });

            const largeRange = sanitizeMarks({
                min: 0,
                max: 10000,
                marks: undefined,
                step: 1000,
                sliderWidth: 330,
            });

            const smallPositions = getMarkPositions(smallRange);
            const largePositions = getMarkPositions(largeRange);

            // Large numbers (5 chars like "10000") should have fewer marks than small numbers (2-3 chars like "10", "100")
            expect(largePositions.length).toBeLessThanOrEqual(
                smallPositions.length
            );

            // Both should be valid steps
            expect(areAllMarksValidSteps(smallRange, 0, 10)).toBe(true);
            expect(areAllMarksValidSteps(largeRange, 0, 1000)).toBe(true);

            // Large range should still have reasonable number of marks (not too few)
            expect(largePositions.length).toBeGreaterThanOrEqual(3);
        });
    });

    describe('Narrow slider behavior', () => {
        test('should show fewer marks than baseline for 100px width', () => {
            const baseline = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 330,
            });

            const narrow = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 100,
            });

            const baselinePositions = getMarkPositions(baseline);
            const narrowPositions = getMarkPositions(narrow);

            expect(narrowPositions.length).toBeLessThan(
                baselinePositions.length
            );
            expect(areAllMarksValidSteps(narrow, 0, 5)).toBe(true);
        });

        test('should show only 0, 50, 100 for very narrow slider (100px)', () => {
            const marks = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 100,
            });

            const positions = getMarkPositions(marks);

            expect(positions).toEqual([0, 50, 100]);
        });
    });

    describe('Wide slider behavior', () => {
        test('should show more marks than baseline for 660px width', () => {
            const baseline = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 330,
            });

            const wide = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 660,
            });

            const baselinePositions = getMarkPositions(baseline);
            const widePositions = getMarkPositions(wide);

            expect(widePositions.length).toBeGreaterThan(
                baselinePositions.length
            );
            expect(areAllMarksValidSteps(wide, 0, 5)).toBe(true);
        });
    });

    describe('Different step values', () => {
        test('should work with step=10', () => {
            const marks = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 10,
                sliderWidth: 330,
            });

            const positions = getMarkPositions(marks);

            expect(areAllMarksValidSteps(marks, 0, 10)).toBe(true);
            expect(positions).toContain(0);
            expect(positions).toContain(100);

            // All positions should be multiples of 10
            positions.forEach(pos => {
                expect(pos % 10).toBe(0);
            });
        });

        test('should reduce density by half for fractional steps', () => {
            const integerStep = sanitizeMarks({
                min: 0,
                max: 10,
                marks: undefined,
                step: 1, // Integer step
                sliderWidth: 330,
            });

            const fractionalStep = sanitizeMarks({
                min: 0,
                max: 10,
                marks: undefined,
                step: 0.5, // Fractional step
                sliderWidth: 330,
            });

            const integerPositions = getMarkPositions(integerStep);
            const fractionalPositions = getMarkPositions(fractionalStep);

            // Fractional step should have roughly half the marks of integer step
            expect(fractionalPositions.length).toBeLessThan(
                integerPositions.length
            );
            expect(fractionalPositions.length).toBeLessThanOrEqual(
                Math.ceil(integerPositions.length / 2) + 1
            );

            // Both should be valid steps
            expect(areAllMarksValidSteps(integerStep, 0, 1)).toBe(true);
            expect(areAllMarksValidSteps(fractionalStep, 0, 0.5)).toBe(true);
        });

        test('should work with fractional step=0.5', () => {
            const marks = sanitizeMarks({
                min: 0,
                max: 5,
                marks: undefined,
                step: 0.5,
                sliderWidth: 330,
            });

            const positions = getMarkPositions(marks);

            expect(areAllMarksValidSteps(marks, 0, 0.5)).toBe(true);
            expect(positions).toContain(0);
            expect(positions).toContain(5);

            // All positions should be multiples of 0.5
            positions.forEach(pos => {
                expect(pos % 0.5).toBeCloseTo(0, 10);
            });
        });
    });

    describe('Edge cases', () => {
        test('should handle undefined sliderWidth', () => {
            const marks = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: undefined,
            });

            const positions = getMarkPositions(marks);

            expect(areAllMarksValidSteps(marks, 0, 5)).toBe(true);
            expect(positions).toContain(0);
            expect(positions).toContain(100);
            expect(positions.length).toBeGreaterThan(0);
        });
    });

    describe('Width scaling behavior', () => {
        test('marks should increase proportionally with width', () => {
            const width100 = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 100,
            });

            const width330 = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 330,
            });

            const width660 = sanitizeMarks({
                min: 0,
                max: 100,
                marks: undefined,
                step: 5,
                sliderWidth: 660,
            });

            const positions100 = getMarkPositions(width100);
            const positions330 = getMarkPositions(width330);
            const positions660 = getMarkPositions(width660);

            // Width increases should generally result in more marks
            expect(positions100.length).toBeLessThanOrEqual(
                positions330.length
            );
            expect(positions330.length).toBeLessThanOrEqual(
                positions660.length
            );

            // All should be valid steps
            expect(areAllMarksValidSteps(width100, 0, 5)).toBe(true);
            expect(areAllMarksValidSteps(width330, 0, 5)).toBe(true);
            expect(areAllMarksValidSteps(width660, 0, 5)).toBe(true);
        });
    });
});
