/* eslint-disable no-magic-numbers */
import {SliderMarks} from '../../src/types';
import {autoGenerateDateMarks} from '../../src/utils/computeDateSliderMarkers';

const getMarkPositions = (marks: SliderMarks): number[] => {
    if (!marks) {
        return [];
    }
    return Object.keys(marks)
        .map(Number)
        .sort((a, b) => a - b);
};

const toUtcTs = (dateStr: string) => {
    const [year, month, day] = dateStr.split('-').map(Number);
    return Date.UTC(year, month - 1, day);
};

describe('autoGenerateDateMarks', () => {
    describe('Basic behavior', () => {
        test('always includes min and max', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const marks = autoGenerateDateMarks(
                min,
                max,
                undefined,
                undefined,
                'YYYY-MM-DD',
                330
            );
            const positions = getMarkPositions(marks);
            expect(positions[0]).toBe(toUtcTs('2026-05-01'));
            expect(positions[positions.length - 1]).toBe(toUtcTs('2026-05-31'));
        });

        test('returns at least min and max for very narrow slider', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const marks = autoGenerateDateMarks(
                min,
                max,
                undefined,
                undefined,
                'YYYY-MM-DD',
                50
            );
            const positions = getMarkPositions(marks);
            expect(positions.length).toBeGreaterThanOrEqual(2);
        });

        test('returns correct mark labels using format string', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-03');
            const marks = autoGenerateDateMarks(
                min,
                max,
                1,
                'days',
                'YYYY-MM-DD',
                1000
            );
            expect(marks[toUtcTs('2026-05-01')]).toBe('2026-05-01');
            expect(marks[toUtcTs('2026-05-02')]).toBe('2026-05-02');
            expect(marks[toUtcTs('2026-05-03')]).toBe('2026-05-03');
        });

        test('handles undefined sliderWidth with a default', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const marks = autoGenerateDateMarks(
                min,
                max,
                undefined,
                undefined,
                'YYYY-MM-DD',
                undefined
            );
            const positions = getMarkPositions(marks);
            expect(positions.length).toBeGreaterThanOrEqual(2);
            expect(positions[0]).toBe(toUtcTs('2026-05-01'));
            expect(positions[positions.length - 1]).toBe(toUtcTs('2026-05-31'));
        });

        test('handles null sliderWidth with a default', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const marks = autoGenerateDateMarks(
                min,
                max,
                undefined,
                undefined,
                'YYYY-MM-DD',
                null
            );
            const positions = getMarkPositions(marks);
            expect(positions.length).toBeGreaterThanOrEqual(2);
        });
    });

    describe('Step behavior', () => {
        test('generates marks on valid step positions (weekly step)', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const marks = autoGenerateDateMarks(
                min,
                max,
                7,
                'days',
                'YYYY-MM-DD',
                1600
            );
            const positions = getMarkPositions(marks);
            for (let i = 1; i < positions.length - 1; i++) {
                const diff =
                    (positions[i] - positions[i - 1]) / (1000 * 60 * 60 * 24);
                expect(diff % 7).toBe(0);
            }
        });

        test('generates marks on valid step positions (every 3 days)', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const marks = autoGenerateDateMarks(
                min,
                max,
                3,
                'days',
                'YYYY-MM-DD',
                1600
            );
            const positions = getMarkPositions(marks);
            for (let i = 1; i < positions.length - 1; i++) {
                const diff =
                    (positions[i] - positions[i - 1]) / (1000 * 60 * 60 * 24);
                expect(diff % 3).toBe(0);
            }
        });

        test('defaults to daily step when no step provided', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-05');
            const marks = autoGenerateDateMarks(
                min,
                max,
                undefined,
                undefined,
                'YYYY-MM-DD',
                1600
            );
            const positions = getMarkPositions(marks);
            for (let i = 1; i < positions.length; i++) {
                const diff =
                    (positions[i] - positions[i - 1]) / (1000 * 60 * 60 * 24);
                expect(diff).toBe(1);
            }
        });
    });

    describe('Width scaling behavior', () => {
        test('wider slider shows more marks than narrow slider', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const narrow = autoGenerateDateMarks(
                min,
                max,
                undefined,
                undefined,
                'YYYY-MM-DD',
                100
            );
            const wide = autoGenerateDateMarks(
                min,
                max,
                undefined,
                undefined,
                'YYYY-MM-DD',
                1000
            );
            expect(getMarkPositions(wide).length).toBeGreaterThanOrEqual(
                getMarkPositions(narrow).length
            );
        });

        test('marks increase proportionally with width', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const w100 = getMarkPositions(
                autoGenerateDateMarks(
                    min,
                    max,
                    undefined,
                    undefined,
                    'YYYY-MM-DD',
                    100
                )
            );
            const w330 = getMarkPositions(
                autoGenerateDateMarks(
                    min,
                    max,
                    undefined,
                    undefined,
                    'YYYY-MM-DD',
                    330
                )
            );
            const w660 = getMarkPositions(
                autoGenerateDateMarks(
                    min,
                    max,
                    undefined,
                    undefined,
                    'YYYY-MM-DD',
                    660
                )
            );
            expect(w100.length).toBeLessThanOrEqual(w330.length);
            expect(w330.length).toBeLessThanOrEqual(w660.length);
        });
    });

    describe('Label format impact on density', () => {
        test('longer format strings result in fewer marks than shorter ones', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-31');
            const shortFormat = getMarkPositions(
                autoGenerateDateMarks(min, max, undefined, undefined, 'DD', 330)
            );
            const longFormat = getMarkPositions(
                autoGenerateDateMarks(
                    min,
                    max,
                    undefined,
                    undefined,
                    'YYYY-MM-DD',
                    330
                )
            );
            expect(longFormat.length).toBeLessThanOrEqual(shortFormat.length);
        });
    });

    describe('Edge cases', () => {
        test('min equals max returns single mark', () => {
            const date = new Date('2026-05-15');
            const marks = autoGenerateDateMarks(
                date,
                date,
                undefined,
                undefined,
                'YYYY-MM-DD',
                330
            );
            const positions = getMarkPositions(marks);
            expect(positions.length).toBe(1);
            expect(positions[0]).toBe(toUtcTs('2026-05-15'));
        });

        test('range of two days returns both marks', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2026-05-02');
            const marks = autoGenerateDateMarks(
                min,
                max,
                undefined,
                undefined,
                'YYYY-MM-DD',
                330
            );
            const positions = getMarkPositions(marks);
            expect(positions).toContain(toUtcTs('2026-05-01'));
            expect(positions).toContain(toUtcTs('2026-05-02'));
        });

        test('large date range with yearly step does not create too many marks', () => {
            const min = new Date('2026-05-01');
            const max = new Date('2056-05-01');
            const marks = autoGenerateDateMarks(
                min,
                max,
                1,
                'years',
                'YYYY-MM-DD',
                330
            );
            const positions = getMarkPositions(marks);
            expect(positions.length).toBeLessThanOrEqual(15);
            expect(positions.length).toBeGreaterThanOrEqual(2);
        });
    });
});
